MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.SatisHarekets.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from x in c.Caris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " +x.CariSoyad,
                                               Value = x.CariID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd +" "+ x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;
            return View();
        }

        [HttpPost]
        public ActionResult YeniSatis(SatisHareket s)
        {
            s.SatisTarih =DateTime.Parse( DateTime.Now.ToShortDateString());
            c.SatisHarekets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from x in c.Caris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;
            var deger = c.SatisHarekets.Find(id);
            return View("SatisGetir", deger);
        }
        public ActionResult SatisGuncelle (SatisHareket p)
        {
            var deger = c.SatisHarekets.Find(p.SatisID);
            deger.CariID = p.CariID;
            deger.SatisAdet = p.SatisAdet;
            deger.SatisFiyat = p.SatisFiyat;
            deger.PersonelID = p.PersonelID;
            deger.SatisTarih = p.SatisTarih;
            deger.SatisToplamTutar = p.SatisToplamTutar;
            deger.UrunID = p.UrunID;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.SatisID == id).ToList();
            return View(degerler);
        }

        public ActionResult SatisListesi()
        {
            var degerler = c.SatisHarekets.ToList();
            return View(degerler);
        }

    }
}

MvcOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table id="tbl1" class="table table-bordered" style="margin-top:20px">
    <thead>

        <tr>
            <th>ID</th>
            <th>Urun</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam Tutar</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Detaylar</th>

        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.SatisID</td>
            <td>@k.Urun.UrunAd</td>
            <td>@k.Cari.CariAd @k.Cari.CariSoyad</td>
            <td>@k.Personel.PersonelAd @k.Personel.PersonelSoyad</td>
            <td>@k.SatisAdet</td>
            <td>@k.SatisFiyat</td>
            <td>@k.SatisToplamTutar</td>
            <td>@k.SatisTarih</td>
            <td><a href="/Satis/SatisGetir/@k.SatisID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Satis/SatisDetay/@k.SatisID" class="btn btn-success" style="background-color:lightcoral">Detay</a></td>
        </tr>
    }


</table>
<a href="/Satis/YeniSatis" class="btn btn-info">Yeni Satış Yap</a>


@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>

$('#tbl1').dataTable({});

</script>

MvcOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Satış Detayı</h2>
<br />

<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SatisID</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Cari.CariAd @x.Cari.CariSoyad</td>
            <td>@x.Personel.PersonelAd  @x.Personel.PersonelSoyad</td>
            <td>@x.SatisFiyat</td>
            <td>@x.SatisAdet</td>
            <td>@x.SatisToplamTutar</td>
            <td>@x.SatisTarih</td>
            
        </tr>
    }

</table>
<a href="/Satis/SatisListesi/" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a>

MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Satış İşlemi Güncelleme</h2>
<br />
@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.SatisID)

        @Html.LabelFor(x => x.Urun)
        @Html.DropDownListFor(x => x.UrunID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })

        <br />
        @Html.Label("Cari")
        @Html.DropDownListFor(x => x.CariID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Personel)
        @Html.DropDownListFor(x => x.PersonelID, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.SatisAdet)
        @Html.TextBoxFor(x => x.SatisAdet, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.SatisFiyat)
        @Html.TextBoxFor(x => x.SatisFiyat, new { @class = "form-control" })
        <br />


        <br />
        @Html.LabelFor(x => x.SatisToplamTutar)
        @Html.TextBoxFor(x => x.SatisToplamTutar, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.SatisTarih)
        @Html.TextBoxFor(x => x.SatisTarih, new { @class = "form-control" })






    </div>

    <button class="btn btn-warning">Güncelle</button>
}

MvcOnlineTicariOtomasyon/Views/Satis/SatisListesi.cshtml
@{
    Layout = null;
}

@using MvcOnlineTicariOtomasyon.Models.Siniflar

@model List<SatisHareket>

@{

    Layout = null;

}

<br />

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>

                <th>Satış Id</th>

                <th>Ürün</th>

                <th>Cari</th>

                <th>Personel</th>

                <th>Fiyat</th>

                <th>Adet</th>

                <th>Toplam</th>

                <th>Tarih</th>

            </tr>

        </thead>

        <tbody>

            @foreach (var x in Model)

            {

                <tr>

                    <td>@x.SatisID</td>

                    <td>@x.Urun.UrunAd</td>

                    <td>@x.Cari.CariAd</td>

                    <td>@x.Personel.PersonelAd  @x.Personel.PersonelSoyad</td>

                    <td>@x.SatisFiyat</td>

                    <td>@x.SatisAdet</td>

                    <td>@x.SatisToplamTutar</td>

                    <td>@x.SatisTarih</td>

                </tr>

            }


        </tbody>

    </table>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>

        $(document).ready(function () {

            var table = $('#example').DataTable({

                lengthChange: false,

                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']

            });


            table.buttons().container()

                .appendTo('#example_wrapper .col-md-6:eq(0)');

        });

    </script>

</body>

</html>

MvcOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Satış Sayfası</h2>
<br />
<form class="form-group" method="post">
    <br />
    @Html.LabelFor(x => x.Urun)
    @Html.DropDownListFor(x => x.UrunID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })

    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.CariID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x => x.PersonelID, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.SatisAdet)
    @Html.TextBoxFor(x => x.SatisAdet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.SatisFiyat)
    @Html.TextBoxFor(x => x.SatisFiyat, new { @class = "form-control" })
    <br />

    <br />
    @Html.LabelFor(x => x.SatisToplamTutar)
    @Html.TextBoxFor(x => x.SatisToplamTutar, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Satış Yap</button>

</form>